spring:
  application:
    name: amy-admin

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB

server:
  port: 8080

auth:
  admin-user-name: admin
  admin-password: $2a$10$YvCHgHk8ldLfKX6.vyE0e.aDV7TRvSs9UAtr4w/xds96lovMKCKy.

jwt:
  secret: aXR4bWpmNHNqdWk4dzJ5dnViYW5oaGlxaHlyenNvdjVxY2U0dHNiY2V3aXBxaGFqMmtrZG1ybnpqc3lwYTRxYmdkNHB2bGg0dDlxMWF5ZjFwYmpydndyNm4yY2Ewc2JkdmtzYXdrM3VycXp3dWFweWh1bXhvYWxzbDJiMnhiZ3A=
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
