spring:
  application:
    name: amy-admin

server:
  port: 8080

auth:
  admin-user-name: admin
  admin-password: $2a$10$YvCHgHk8ldLfKX6.vyE0e.aDV7TRvSs9UAtr4w/xds96lovMKCKy.

jwt:
  secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
